### PR TITLE
Put all the test code in the test files

### PR DESCRIPTION
**Pull request by nathanjsweet**

### CODE REVIEW

**Comment by nathanjsweet** [comment]
Builds and tests pass fine.

**Comment by lmb** [comment]
I think we should keep these functions exported. I want to use them from my own Go userspace to test the XDP programs I'm using. This lets me unit test my kernel code from the go test runner.

**Comment by nathanjsweet** [comment]
I changed it to be a special file that won't be added if a "prod" build flag is added.

**Comment by lmb** [comment]
Im currently out of the country, so I can review until end of next week, 
sorry. l find build tags are difficult to work with, so maybe we simply 
move the functions into a sub package?

On 20 April 2018 22:44:50 Nathan Sweet <notifications@github.com> wrote:
I changed it to be a special file that won't be added if a "prod" build 
flag is added.

**Comment by nathanjsweet** [comment]
Yeah they will be. It's really not a big issue. If the test functions ever get large we can pull them out later.

**Pull request closed without merging**
