### PR TITLE
Support reading bpf_perf_event_output from user space

### PR DESCRIPTION
**Pull request by lmb**
Add an API to read perf ring buffers from userspace. This is intented to be used with `bpf_perf_event_output`, not as a general purpose perf event wrapper.

There is still a bug here where bpf_perf_event_output returns EOPNOTSUPP sometimes, so this isn't ready to merge yet.

### CODE REVIEW

**Comment by lmb** [comment]
Well, `bpf_perf_event_output` is available in a few BPF program types. It needs users pace support to be usable though, and requires integrating with PerfEventArray. Hence this PR.

**Comment by nathanjsweet** [comment]
Okay. :)

**Comment by nathanjsweet** [comment]
Why did you get rid of the tracepoint code?

**Comment by lmb** [comment]
Happy to move the commit to a separate PR if you want to discuss this more.

* No tests
* I couldn't fully understand how to use it from the doc
* It looks like the API leaks the event FD, so there is no way to remove 
events except restarting the process

**Pull request merged**
